// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'admin_dashboard';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String AVATAR_1 = 'assets/images/avatar_1.svg';
}
